web: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn prepiq.wsgi:application --bind 0.0.0.0:$PORT --workers ${WEB_CONCURRENCY:-3} --timeout 30
worker: celery -A prepiq worker --loglevel=info
