# Generated by Django 4.2.30 on 2026-07-03 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume_sessions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_filename', models.CharField(max_length=255)),
                ('resume_text', resume_sessions.fields.EncryptedTextField()),
                ('job_role', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Technical', 'Technical Questions'), ('Project-Based', 'Project-Based Questions'), ('Behavioral', 'Behavioral Questions'), ('Role-Specific', 'Role-Specific Conceptual Questions')], max_length=50)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('why_asked', models.TextField()),
                ('ideal_answer_outline', models.JSONField()),
                ('order_index', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='resume_sessions.resumesession')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('session', 'order_index')},
            },
        ),
    ]
