# Generated by Django 4.2.30 on 2026-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='ideal_answer_outline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
