# Generated by Django 4.2.30 on 2026-07-03 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField()),
                ('question_mix', models.CharField(max_length=20)),
                ('time_limit_per_question', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('question_order', models.JSONField()),
                ('current_question_index', models.IntegerField(default=0)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('hiring_recommendation', models.CharField(blank=True, choices=[('Strong Yes', 'Strong Yes'), ('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], max_length=20, null=True)),
                ('full_report', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocks', to='resume_sessions.resumesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('was_skipped', models.BooleanField(default=False)),
                ('was_timed_out', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('per_question_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('per_question_feedback', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('mock_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mock.mockinterview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_sessions.interviewquestion')),
            ],
            options={
                'unique_together': {('mock_interview', 'question')},
            },
        ),
    ]
