# Generated by Django 4.2.30 on 2026-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterview',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
